server:
  port: 8082

### config he thong

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flower?useSSL=false&serverTimezone=GMT%2B7&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: quang1998
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

#        cấu hình để log chi tiết hơn
logging:
  level:
    root=DEBUG:


# cấu hình để thay đổi DB tu nơi khác không cần cố định trong code
#jdbc:
#  mysql:
#    url=jdbc:mysql://host1:33060/loda:

